### ISSUE TITLE
 The last dimension is not 1

### ISSUE THREAD

**Issue by xiewenxin** [opensourceai/MRI-U-net#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xiewenxin** [comment]
if x.shape[-1] == 1:
      
        x_tiled = np.tile(x, (1, 1, 1, classes_num))

        for i in range(classes_num):
            x_tiled[:, :, :, i] = np.where(x_tiled[:, :, :, i] == i, 1, 0)

    else:
        raise IndexError("The last dimension is not 1")
    return x_tiled


麻烦大兄弟帮忙看看，运行到这里报错了。不知道下一步怎么进行。自己理论还没看。

**Comment by chenquan** [comment]
报错的全部内容发一下看看

**Comment by chenquan** [comment]
这是一个bug已经修正了，你重新clone一下代码吧

**Comment by xiewenxin** [comment]
你修改的内容我之前已经改过了。应该不是那个问题。
报错内容：
 File "E:\github-project\MRI-U-net-master\src\utils.py", line 68, in get_data
    label = encode_one_hot(label, 3)

  File "E:\github-project\MRI-U-net-master\src\utils.py", line 88, in encode_one_hot
    raise IndexError("The last dimension is not 1")

IndexError: The last dimension is not 1

代码部分，我修改了一些内容：
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
import numpy as np
import h5py
from scipy import ndimage


# 加载数据
def _load(path_name):
    """

    :param path_name:
    :return:
    """
    import os
    if not os.path.exists("../data/images.h5"):

        images = []
        for i in range(1,221):
            now_file_path = "../data/Image/IM" + str(i) + ".png"
            image = np.array(ndimage.imread(now_file_path, flatten=False))
            images.append(image)  # images shape=(m,64,64,3)
        images = np.array(images, copy=True)
        file = h5py.File('../data/images.h5', 'w')  # 创建HDF5文件
        file.create_dataset('../data/images.h5', data=images)  # 写入
        file.close()
    else:
        with h5py.File('../data/images.h5', 'r') as flie:
            images = flie.get("images")
            images = np.array(images, dtype=np.float32)

    if not os.path.exists("../data/labels.h5"):
        labels = []
        for i in range(1, 221):
            now_file_path = "../data/Label/Label" + str(i) + ".png"
            label = np.array(ndimage.imread(now_file_path, flatten=False))
            labels.append(label)  # images shape=(m,64,64,3)
        labels = np.array(labels, copy=True)
        file = h5py.File('../data/labels.h5', 'w')  # 创建HDF5文件
        file.create_dataset('labels', data=labels)  # 写入
        file.close()

    else:
        with h5py.File('../data/labels.h5', 'r') as flie:
            labels = flie.get("labels")
            labels = np.array(labels, dtype=np.float32)
   # images = images.astype('float32')
    images /= 255
    train_image = np.expand_dims(images[:], -1)
    train_label = labels[:]
    del images, labels
    return train_image, train_label


def get_data(path_name):
    image, label = _load(path_name)
    label[label == 128] = 1  # 膀胱壁区域
    label[label == 255] = 2  # 肿瘤区域
 
    # one_hot 处理
    # label shape = (n,512,512,1)
    label = encode_one_hot(label, 3)

    return image, label


def encode_one_hot(x, classes_num=3):
    """
    :param array x: ,Single channel picture.
    :param int classes_num: Dimension of one_hot or Classification number.
    :return: label of one_hot
    :rtype: narray
    """
    if x.shape[-1] == 1:
      
        x_tiled = np.tile(x, (1, 1, 1, classes_num))

        for i in range(classes_num):
            x_tiled[:, :, :, i] = np.where(x_tiled[:, :, :, i] == i, 1, 0)

    else:
        raise IndexError("The last dimension is not 1")
    return x_tiled


# 划分训练集和测试集
def split_train_test(X, y, test_size=0.33, random_state=42):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size, random_state)
    return X_train, X_test, y_train, y_test


# 打乱数据顺序
def shuffle_data(X, y, random_state=0, n_samples=None):
    X, y = shuffle(X, y, random_state, n_samples)
    return X, y

**Comment by chenquan** [comment]
你看一下你的原始数据最后一个维度的值是不是1如果不是1就会抛异常，这是我设置的异常抛出机制，不是代码错误。
