### ISSUE TITLE
您好 训练好的模型失效了

### ISSUE THREAD

**Issue by qsr111111** [opensourceai/MRI-U-net#11]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by qsr111111** [comment]
另外 想请问一下为什么会出现这个错误
D:\acaconda\python.exe D:/git/MRI-U-net-master/src/Main.py
=========          Get data            =========
(2200, 256, 256, 1)
(2200, 512, 512, 1)
(2200, 512, 512, 1)
=========Split train sets and test sets=========
=========          Build model         =========
=========       Start train model      =========
Traceback (most recent call last):
  File "D:/git/MRI-U-net-master/src/Main.py", line 28, in <module>
    model.fit(X_train, y_train, batch_size=BATCH_SIZE, epochs=10, validation_split=0.01, callbacks=[ModelCheckpoint])
  File "D:\git\MRI-U-net-master\src\UNetKeras.py", line 102, in fit
    class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps)
  File "D:\acaconda\lib\site-packages\tensorflow\python\keras\engine\training.py", line 709, in fit
    shuffle=shuffle)
  File "D:\acaconda\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2692, in _standardize_user_data
    y, self._feed_loss_fns, feed_output_shapes)
  File "D:\acaconda\lib\site-packages\tensorflow\python\keras\engine\training_utils.py", line 549, in check_loss_and_target_compatibility
    ' while using as loss `' + loss_name + '`. '
ValueError: A target array with shape (2178, 512, 512, 3) was passed for an output of shape (None, 256, 256, 3) while using as loss `categorical_crossentropy`. This loss expects targets to have the same shape as the output.

Process finished with exit code 1

**Comment by chenquan** [comment]
> 另外 想请问一下为什么会出现这个错误
> D:\acaconda\python.exe D:/git/MRI-U-net-master/src/Main.py
> ========= Get data =========
> (2200, 256, 256, 1)
> (2200, 512, 512, 1)
> (2200, 512, 512, 1)
> =========Split train sets and test sets=========
> ========= Build model =========
> ========= Start train model =========
> Traceback (most recent call last):
> File "D:/git/MRI-U-net-master/src/Main.py", line 28, in
> model.fit(X_train, y_train, batch_size=BATCH_SIZE, epochs=10, validation_split=0.01, callbacks=[ModelCheckpoint])
> File "D:\git\MRI-U-net-master\src\UNetKeras.py", line 102, in fit
> class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps)
> File "D:\acaconda\lib\site-packages\tensorflow\python\keras\engine\training.py", line 709, in fit
> shuffle=shuffle)
> File "D:\acaconda\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2692, in _standardize_user_data
> y, self._feed_loss_fns, feed_output_shapes)
> File "D:\acaconda\lib\site-packages\tensorflow\python\keras\engine\training_utils.py", line 549, in check_loss_and_target_compatibility
> ' while using as loss `' + loss_name + '`. '
> ValueError: A target array with shape (2178, 512, 512, 3) was passed for an output of shape (None, 256, 256, 3) while using as loss `categorical_crossentropy`. This loss expects targets to have the same shape as the output.
> 
> Process finished with exit code 1

https://github.com/opensourceai/MRI-U-net/blob/07b37347a81b9e622a0c65733ec23dd526b7d316/src/utils.py#L13
尝试修改 `image_h_w = 512`
