### ISSUE TITLE
您好,訓練用的資料連結已使效,能否重新提供,謝謝

### ISSUE THREAD

**Issue by hotqstan** [opensourceai/MRI-U-net#12]
https://pan.baidu.com/s/1NhLubIXS6SU_PFzNjmLZPQ
此連結無法下載

**Comment by chenquan** [comment]
> https://pan.baidu.com/s/1NhLubIXS6SU_PFzNjmLZPQ
> 此連結無法下載

链接: https://pan.baidu.com/s/1CqS5-LRjwRfhqQgW8N_sqg 提取码: iryj 复制这段内容后打开百度网盘手机App，操作更方便哦
