### ISSUE TITLE
模型连接失效

### ISSUE THREAD

**Issue by neil3212080** [opensourceai/MRI-U-net#3]

**Comment by chenquan** [comment]
链接:https://pan.baidu.com/s/1xW8LgUWLpkdMcBhUMU-n9A 提取码:e5x7

**Comment by zhangruifang123** [comment]
您好，链接提取码错误，可以重新分享一下吗？谢谢

**Comment by sunt40** [comment]
提取码错误 @chenquan

**Comment by chenquan** [comment]
> 提取码错误 @chenquan

等我重新找文件分享

**Comment by KakiWei** [comment]
> 

同求

**Comment by chenquan** [comment]
链接: https://pan.baidu.com/s/1JDA9AdVdReA6JhED_eQS9g?pwd=fars 提取码: fars 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by Epiphany9758** [comment]
请问.hdf5这个模型文件如何使用，怎样才可以看到model.py的内容？
