### ISSUE TITLE
关于重现该代码时出现的“数组”问题

### ISSUE THREAD

**Issue by Jai-wei** [opensourceai/MRI-U-net#4]
Inputs to operation training_8/Adam/gradients/AddN_4 of type _MklAddN must have the same size and shape.  Input 0: [1,64,64,512] != input 1: [2097152]
[[Node: training_8/Adam/gradients/AddN_4 = _MklAddN[N=2, T=DT_FLOAT, _kernel="MklOp", _device="/job:localhost/replica:0/task:0/device:CPU:0"](training_8/Adam/gradients/concatenate_32/concat_grad/Slice, training_8/Adam/gradients/max_pooling2d_35/MaxPool_grad/MaxPoolGrad, DMT/_251, training_8/Adam/gradients/max_pooling2d_35/MaxPool_grad/MaxPoolGrad:1)]]

**Comment by chenquan** [comment]
@2567366108 请检查你的版本。TensorFlow的API变动有点儿大，建议使用以下版本。

||版本|
|---|---|
|TensorFlow |1.8.0|
|cuda |9.0|
|cudann |v7|
|win10|x64|

**Comment by chenquan** [comment]
@2567366108 如果解决了麻烦告知。

**Comment by Jai-wei** [comment]
好的，大概于明天再次重现，感谢您的解答~




------------------ 原始邮件 ------------------
发件人: "Chen Quan"<notifications@github.com>;
发送时间: 2019年4月18日(星期四) 晚上7:07
收件人: "ChenQuan/MRI-U-net"<MRI-U-net@noreply.github.com>;
抄送: "　⃢👁━👁⃢　"<2567366108@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ChenQuan/MRI-U-net] 关于重现该代码时出现的“数组”问题 (#4)




@2567366108 如果解决了麻烦告知。

**Comment by chenquan** [comment]
好的，有什么问题，欢迎issues。


 
---原始邮件---
发件人: "Jaiwei"<notifications@github.com>
发送时间: 2019年4月18日(星期四) 晚上7:10
收件人: "ChenQuan/MRI-U-net"<MRI-U-net@noreply.github.com>;
抄送: "Assign"<assign@noreply.github.com>;"Chen Quan"<chenquan@osai.club>;
主题: Re: [ChenQuan/MRI-U-net] 关于重现该代码时出现的“数组”问题 (#4)


好的，大概于明天再次重现，感谢您的解答~ 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "Chen Quan"<notifications@github.com>; 
 发送时间: 2019年4月18日(星期四) 晚上7:07 
 收件人: "ChenQuan/MRI-U-net"<MRI-U-net@noreply.github.com>; 
 抄送: "　⃢👁━👁⃢　"<2567366108@qq.com>; "Mention"<mention@noreply.github.com>;  
 主题: Re: [ChenQuan/MRI-U-net] 关于重现该代码时出现的“数组”问题 (#4) 
 
 
 
 
 @2567366108 如果解决了麻烦告知。
