### ISSUE TITLE
模型无效（已自己解决= =）

### ISSUE THREAD

**Issue by huangxiao1234** [opensourceai/MRI-U-net#5]

**Comment by huangxiao1234** [comment]
额好吧，虽然准确率有98+，其实是因为需要正确识别并分割的部分太少了，所以准确率很高。。。。所以10次迭代训练出来的模型应该没什么用

**Comment by chenquan** [comment]
您好，可以贡献您的方案吗？说不定其他朋友也有这个问题。

**Comment by huangxiao1234** [comment]
> 您好，可以贡献您的方案吗？说不定其他朋友也有这个问题。

嗯嗯。我也就重新训练了一个，之前那个不知道为啥我反正跑不出结果。模型链接如下。
链接：https://pan.baidu.com/s/1r30YpmvH3EQpHa0dDKkBqQ 
提取码：tetn 
=====================================
使用方法：
        model = UNetKeras()
	model.compile()
	model.load_weights("model_final_time.h5")
	pred = model.predict(X_test)

此时的pred不需要reshape

**Comment by chenquan** [comment]
@huangxiao1234 感谢

**Comment by KakiWei** [comment]
> > 您好，可以贡献您的方案吗？说不定其他朋友也有这个问题。
> 
> # 嗯嗯。我也就重新训练了一个，之前那个不知道为啥我反正跑不出结果。模型链接如下。
> 链接：https://pan.baidu.com/s/1r30YpmvH3EQpHa0dDKkBqQ
> 提取码：tetn
> 使用方法： model = UNetKeras() model.compile() model.load_weights("model_final_time.h5") pred = model.predict(X_test)
> 
> 此时的pred不需要reshape

链接失效了，可以麻烦您再发一次吗？万分感谢！！！！！

**Comment by Epiphany9758** [comment]
链接失效了，可以麻烦您再发一次吗？万分感谢！！！！！

**Comment by chenquan** [comment]
> 链接失效了，可以麻烦您再发一次吗？万分感谢！！！！！

https://github.com/opensourceai/MRI-U-net/issues/3
https://github.com/opensourceai/MRI-U-net/issues/12

**Comment by Epiphany9758** [comment]
请问有data里面的链接吗？那个也过期了

**Comment by chenquan** [comment]
> 请问有data里面的链接吗？那个也过期了

链接: https://pan.baidu.com/s/1CqS5-LRjwRfhqQgW8N_sqg 提取码: iryj
