### ISSUE TITLE
关于模型报错信息

### ISSUE THREAD

**Issue by hongweidonga** [opensourceai/MRI-U-net#9]
您好，萌新小白一枚，有如下疑问：
报错信息：
ValueError: A target array with shape (2178, 512, 512, 3) was passed for an output of shape (None, 256, 256, 3) while using as loss `categorical_crossentropy`. This loss expects targets to have the same shape as the output.
在 UNetKeras.py 中 self.model.fit(x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps)
一行中报错，请问这个是不是模型失效的原因？

**Comment by chenquan** [comment]
传入数据的图片的大小与模型定义的不符.检查一下你的图片大小.

**Comment by hongweidonga** [comment]
data集里的数据都是按照 Readme.md 中的链接直接下载的，为何会出现图片大小不匹配？

**Comment by chenquan** [comment]
https://github.com/opensourceai/MRI-U-net/blob/026a57311dc20e96ec24638b9c3faaf9a2022fe8/src/utils.py#L30

加载数据时,对图片的尺寸进行了`resize`, 检查一下你的相关设置
